program test_session_large_symbol_count_compiler
    use ffc_test_support, only: expect_exit_status
    implicit none

    print *, '=== direct session large symbol count test ==='

    if (.not. test_200_symbols()) stop 1

    print *, 'PASS: 200 symbols lower without hitting any cap'
contains

    logical function test_200_symbols()
        character(len=*), parameter :: source = &
            'program main'//new_line('a')// &
            'integer :: sym_1'//new_line('a')// &
            'integer :: sym_2'//new_line('a')// &
            'integer :: sym_3'//new_line('a')// &
            'integer :: sym_4'//new_line('a')// &
            'integer :: sym_5'//new_line('a')// &
            'integer :: sym_6'//new_line('a')// &
            'integer :: sym_7'//new_line('a')// &
            'integer :: sym_8'//new_line('a')// &
            'integer :: sym_9'//new_line('a')// &
            'integer :: sym_10'//new_line('a')// &
            'integer :: sym_11'//new_line('a')// &
            'integer :: sym_12'//new_line('a')// &
            'integer :: sym_13'//new_line('a')// &
            'integer :: sym_14'//new_line('a')// &
            'integer :: sym_15'//new_line('a')// &
            'integer :: sym_16'//new_line('a')// &
            'integer :: sym_17'//new_line('a')// &
            'integer :: sym_18'//new_line('a')// &
            'integer :: sym_19'//new_line('a')// &
            'integer :: sym_20'//new_line('a')// &
            'integer :: sym_21'//new_line('a')// &
            'integer :: sym_22'//new_line('a')// &
            'integer :: sym_23'//new_line('a')// &
            'integer :: sym_24'//new_line('a')// &
            'integer :: sym_25'//new_line('a')// &
            'integer :: sym_26'//new_line('a')// &
            'integer :: sym_27'//new_line('a')// &
            'integer :: sym_28'//new_line('a')// &
            'integer :: sym_29'//new_line('a')// &
            'integer :: sym_30'//new_line('a')// &
            'integer :: sym_31'//new_line('a')// &
            'integer :: sym_32'//new_line('a')// &
            'integer :: sym_33'//new_line('a')// &
            'integer :: sym_34'//new_line('a')// &
            'integer :: sym_35'//new_line('a')// &
            'integer :: sym_36'//new_line('a')// &
            'integer :: sym_37'//new_line('a')// &
            'integer :: sym_38'//new_line('a')// &
            'integer :: sym_39'//new_line('a')// &
            'integer :: sym_40'//new_line('a')// &
            'integer :: sym_41'//new_line('a')// &
            'integer :: sym_42'//new_line('a')// &
            'integer :: sym_43'//new_line('a')// &
            'integer :: sym_44'//new_line('a')// &
            'integer :: sym_45'//new_line('a')// &
            'integer :: sym_46'//new_line('a')// &
            'integer :: sym_47'//new_line('a')// &
            'integer :: sym_48'//new_line('a')// &
            'integer :: sym_49'//new_line('a')// &
            'integer :: sym_50'//new_line('a')// &
            'integer :: sym_51'//new_line('a')// &
            'integer :: sym_52'//new_line('a')// &
            'integer :: sym_53'//new_line('a')// &
            'integer :: sym_54'//new_line('a')// &
            'integer :: sym_55'//new_line('a')// &
            'integer :: sym_56'//new_line('a')// &
            'integer :: sym_57'//new_line('a')// &
            'integer :: sym_58'//new_line('a')// &
            'integer :: sym_59'//new_line('a')// &
            'integer :: sym_60'//new_line('a')// &
            'integer :: sym_61'//new_line('a')// &
            'integer :: sym_62'//new_line('a')// &
            'integer :: sym_63'//new_line('a')// &
            'integer :: sym_64'//new_line('a')// &
            'integer :: sym_65'//new_line('a')// &
            'integer :: sym_66'//new_line('a')// &
            'integer :: sym_67'//new_line('a')// &
            'integer :: sym_68'//new_line('a')// &
            'integer :: sym_69'//new_line('a')// &
            'integer :: sym_70'//new_line('a')// &
            'integer :: sym_71'//new_line('a')// &
            'integer :: sym_72'//new_line('a')// &
            'integer :: sym_73'//new_line('a')// &
            'integer :: sym_74'//new_line('a')// &
            'integer :: sym_75'//new_line('a')// &
            'integer :: sym_76'//new_line('a')// &
            'integer :: sym_77'//new_line('a')// &
            'integer :: sym_78'//new_line('a')// &
            'integer :: sym_79'//new_line('a')// &
            'integer :: sym_80'//new_line('a')// &
            'integer :: sym_81'//new_line('a')// &
            'integer :: sym_82'//new_line('a')// &
            'integer :: sym_83'//new_line('a')// &
            'integer :: sym_84'//new_line('a')// &
            'integer :: sym_85'//new_line('a')// &
            'integer :: sym_86'//new_line('a')// &
            'integer :: sym_87'//new_line('a')// &
            'integer :: sym_88'//new_line('a')// &
            'integer :: sym_89'//new_line('a')// &
            'integer :: sym_90'//new_line('a')// &
            'integer :: sym_91'//new_line('a')// &
            'integer :: sym_92'//new_line('a')// &
            'integer :: sym_93'//new_line('a')// &
            'integer :: sym_94'//new_line('a')// &
            'integer :: sym_95'//new_line('a')// &
            'integer :: sym_96'//new_line('a')// &
            'integer :: sym_97'//new_line('a')// &
            'integer :: sym_98'//new_line('a')// &
            'integer :: sym_99'//new_line('a')// &
            'integer :: sym_100'//new_line('a')// &
            'integer :: sym_101'//new_line('a')// &
            'integer :: sym_102'//new_line('a')// &
            'integer :: sym_103'//new_line('a')// &
            'integer :: sym_104'//new_line('a')// &
            'integer :: sym_105'//new_line('a')// &
            'integer :: sym_106'//new_line('a')// &
            'integer :: sym_107'//new_line('a')// &
            'integer :: sym_108'//new_line('a')// &
            'integer :: sym_109'//new_line('a')// &
            'integer :: sym_110'//new_line('a')// &
            'integer :: sym_111'//new_line('a')// &
            'integer :: sym_112'//new_line('a')// &
            'integer :: sym_113'//new_line('a')// &
            'integer :: sym_114'//new_line('a')// &
            'integer :: sym_115'//new_line('a')// &
            'integer :: sym_116'//new_line('a')// &
            'integer :: sym_117'//new_line('a')// &
            'integer :: sym_118'//new_line('a')// &
            'integer :: sym_119'//new_line('a')// &
            'integer :: sym_120'//new_line('a')// &
            'integer :: sym_121'//new_line('a')// &
            'integer :: sym_122'//new_line('a')// &
            'integer :: sym_123'//new_line('a')// &
            'integer :: sym_124'//new_line('a')// &
            'integer :: sym_125'//new_line('a')// &
            'integer :: sym_126'//new_line('a')// &
            'integer :: sym_127'//new_line('a')// &
            'integer :: sym_128'//new_line('a')// &
            'integer :: sym_129'//new_line('a')// &
            'integer :: sym_130'//new_line('a')// &
            'integer :: sym_131'//new_line('a')// &
            'integer :: sym_132'//new_line('a')// &
            'integer :: sym_133'//new_line('a')// &
            'integer :: sym_134'//new_line('a')// &
            'integer :: sym_135'//new_line('a')// &
            'integer :: sym_136'//new_line('a')// &
            'integer :: sym_137'//new_line('a')// &
            'integer :: sym_138'//new_line('a')// &
            'integer :: sym_139'//new_line('a')// &
            'integer :: sym_140'//new_line('a')// &
            'integer :: sym_141'//new_line('a')// &
            'integer :: sym_142'//new_line('a')// &
            'integer :: sym_143'//new_line('a')// &
            'integer :: sym_144'//new_line('a')// &
            'integer :: sym_145'//new_line('a')// &
            'integer :: sym_146'//new_line('a')// &
            'integer :: sym_147'//new_line('a')// &
            'integer :: sym_148'//new_line('a')// &
            'integer :: sym_149'//new_line('a')// &
            'integer :: sym_150'//new_line('a')// &
            'integer :: sym_151'//new_line('a')// &
            'integer :: sym_152'//new_line('a')// &
            'integer :: sym_153'//new_line('a')// &
            'integer :: sym_154'//new_line('a')// &
            'integer :: sym_155'//new_line('a')// &
            'integer :: sym_156'//new_line('a')// &
            'integer :: sym_157'//new_line('a')// &
            'integer :: sym_158'//new_line('a')// &
            'integer :: sym_159'//new_line('a')// &
            'integer :: sym_160'//new_line('a')// &
            'integer :: sym_161'//new_line('a')// &
            'integer :: sym_162'//new_line('a')// &
            'integer :: sym_163'//new_line('a')// &
            'integer :: sym_164'//new_line('a')// &
            'integer :: sym_165'//new_line('a')// &
            'integer :: sym_166'//new_line('a')// &
            'integer :: sym_167'//new_line('a')// &
            'integer :: sym_168'//new_line('a')// &
            'integer :: sym_169'//new_line('a')// &
            'integer :: sym_170'//new_line('a')// &
            'integer :: sym_171'//new_line('a')// &
            'integer :: sym_172'//new_line('a')// &
            'integer :: sym_173'//new_line('a')// &
            'integer :: sym_174'//new_line('a')// &
            'integer :: sym_175'//new_line('a')// &
            'integer :: sym_176'//new_line('a')// &
            'integer :: sym_177'//new_line('a')// &
            'integer :: sym_178'//new_line('a')// &
            'integer :: sym_179'//new_line('a')// &
            'integer :: sym_180'//new_line('a')// &
            'integer :: sym_181'//new_line('a')// &
            'integer :: sym_182'//new_line('a')// &
            'integer :: sym_183'//new_line('a')// &
            'integer :: sym_184'//new_line('a')// &
            'integer :: sym_185'//new_line('a')// &
            'integer :: sym_186'//new_line('a')// &
            'integer :: sym_187'//new_line('a')// &
            'integer :: sym_188'//new_line('a')// &
            'integer :: sym_189'//new_line('a')// &
            'integer :: sym_190'//new_line('a')// &
            'integer :: sym_191'//new_line('a')// &
            'integer :: sym_192'//new_line('a')// &
            'integer :: sym_193'//new_line('a')// &
            'integer :: sym_194'//new_line('a')// &
            'integer :: sym_195'//new_line('a')// &
            'integer :: sym_196'//new_line('a')// &
            'integer :: sym_197'//new_line('a')// &
            'integer :: sym_198'//new_line('a')// &
            'integer :: sym_199'//new_line('a')// &
            'integer :: sym_200'//new_line('a')// &
            'sym_1 = 1'//new_line('a')// &
            'sym_2 = 2'//new_line('a')// &
            'sym_3 = 3'//new_line('a')// &
            'sym_4 = 4'//new_line('a')// &
            'sym_5 = 5'//new_line('a')// &
            'sym_6 = 6'//new_line('a')// &
            'sym_7 = 7'//new_line('a')// &
            'sym_8 = 8'//new_line('a')// &
            'sym_9 = 9'//new_line('a')// &
            'sym_10 = 10'//new_line('a')// &
            'sym_11 = 11'//new_line('a')// &
            'sym_12 = 12'//new_line('a')// &
            'sym_13 = 13'//new_line('a')// &
            'sym_14 = 14'//new_line('a')// &
            'sym_15 = 15'//new_line('a')// &
            'sym_16 = 16'//new_line('a')// &
            'sym_17 = 17'//new_line('a')// &
            'sym_18 = 18'//new_line('a')// &
            'sym_19 = 19'//new_line('a')// &
            'sym_20 = 20'//new_line('a')// &
            'sym_21 = 21'//new_line('a')// &
            'sym_22 = 22'//new_line('a')// &
            'sym_23 = 23'//new_line('a')// &
            'sym_24 = 24'//new_line('a')// &
            'sym_25 = 25'//new_line('a')// &
            'sym_26 = 26'//new_line('a')// &
            'sym_27 = 27'//new_line('a')// &
            'sym_28 = 28'//new_line('a')// &
            'sym_29 = 29'//new_line('a')// &
            'sym_30 = 30'//new_line('a')// &
            'sym_31 = 31'//new_line('a')// &
            'sym_32 = 32'//new_line('a')// &
            'sym_33 = 33'//new_line('a')// &
            'sym_34 = 34'//new_line('a')// &
            'sym_35 = 35'//new_line('a')// &
            'sym_36 = 36'//new_line('a')// &
            'sym_37 = 37'//new_line('a')// &
            'sym_38 = 38'//new_line('a')// &
            'sym_39 = 39'//new_line('a')// &
            'sym_40 = 40'//new_line('a')// &
            'sym_41 = 41'//new_line('a')// &
            'sym_42 = 42'//new_line('a')// &
            'sym_43 = 43'//new_line('a')// &
            'sym_44 = 44'//new_line('a')// &
            'sym_45 = 45'//new_line('a')// &
            'sym_46 = 46'//new_line('a')// &
            'sym_47 = 47'//new_line('a')// &
            'sym_48 = 48'//new_line('a')// &
            'sym_49 = 49'//new_line('a')// &
            'sym_50 = 50'//new_line('a')// &
            'sym_51 = 51'//new_line('a')// &
            'sym_52 = 52'//new_line('a')// &
            'sym_53 = 53'//new_line('a')// &
            'sym_54 = 54'//new_line('a')// &
            'sym_55 = 55'//new_line('a')// &
            'sym_56 = 56'//new_line('a')// &
            'sym_57 = 57'//new_line('a')// &
            'sym_58 = 58'//new_line('a')// &
            'sym_59 = 59'//new_line('a')// &
            'sym_60 = 60'//new_line('a')// &
            'sym_61 = 61'//new_line('a')// &
            'sym_62 = 62'//new_line('a')// &
            'sym_63 = 63'//new_line('a')// &
            'sym_64 = 64'//new_line('a')// &
            'sym_65 = 65'//new_line('a')// &
            'sym_66 = 66'//new_line('a')// &
            'sym_67 = 67'//new_line('a')// &
            'sym_68 = 68'//new_line('a')// &
            'sym_69 = 69'//new_line('a')// &
            'sym_70 = 70'//new_line('a')// &
            'sym_71 = 71'//new_line('a')// &
            'sym_72 = 72'//new_line('a')// &
            'sym_73 = 73'//new_line('a')// &
            'sym_74 = 74'//new_line('a')// &
            'sym_75 = 75'//new_line('a')// &
            'sym_76 = 76'//new_line('a')// &
            'sym_77 = 77'//new_line('a')// &
            'sym_78 = 78'//new_line('a')// &
            'sym_79 = 79'//new_line('a')// &
            'sym_80 = 80'//new_line('a')// &
            'sym_81 = 81'//new_line('a')// &
            'sym_82 = 82'//new_line('a')// &
            'sym_83 = 83'//new_line('a')// &
            'sym_84 = 84'//new_line('a')// &
            'sym_85 = 85'//new_line('a')// &
            'sym_86 = 86'//new_line('a')// &
            'sym_87 = 87'//new_line('a')// &
            'sym_88 = 88'//new_line('a')// &
            'sym_89 = 89'//new_line('a')// &
            'sym_90 = 90'//new_line('a')// &
            'sym_91 = 91'//new_line('a')// &
            'sym_92 = 92'//new_line('a')// &
            'sym_93 = 93'//new_line('a')// &
            'sym_94 = 94'//new_line('a')// &
            'sym_95 = 95'//new_line('a')// &
            'sym_96 = 96'//new_line('a')// &
            'sym_97 = 97'//new_line('a')// &
            'sym_98 = 98'//new_line('a')// &
            'sym_99 = 99'//new_line('a')// &
            'sym_100 = 100'//new_line('a')// &
            'sym_101 = 101'//new_line('a')// &
            'sym_102 = 102'//new_line('a')// &
            'sym_103 = 103'//new_line('a')// &
            'sym_104 = 104'//new_line('a')// &
            'sym_105 = 105'//new_line('a')// &
            'sym_106 = 106'//new_line('a')// &
            'sym_107 = 107'//new_line('a')// &
            'sym_108 = 108'//new_line('a')// &
            'sym_109 = 109'//new_line('a')// &
            'sym_110 = 110'//new_line('a')// &
            'sym_111 = 111'//new_line('a')// &
            'sym_112 = 112'//new_line('a')// &
            'sym_113 = 113'//new_line('a')// &
            'sym_114 = 114'//new_line('a')// &
            'sym_115 = 115'//new_line('a')// &
            'sym_116 = 116'//new_line('a')// &
            'sym_117 = 117'//new_line('a')// &
            'sym_118 = 118'//new_line('a')// &
            'sym_119 = 119'//new_line('a')// &
            'sym_120 = 120'//new_line('a')// &
            'sym_121 = 121'//new_line('a')// &
            'sym_122 = 122'//new_line('a')// &
            'sym_123 = 123'//new_line('a')// &
            'sym_124 = 124'//new_line('a')// &
            'sym_125 = 125'//new_line('a')// &
            'sym_126 = 126'//new_line('a')// &
            'sym_127 = 127'//new_line('a')// &
            'sym_128 = 128'//new_line('a')// &
            'sym_129 = 129'//new_line('a')// &
            'sym_130 = 130'//new_line('a')// &
            'sym_131 = 131'//new_line('a')// &
            'sym_132 = 132'//new_line('a')// &
            'sym_133 = 133'//new_line('a')// &
            'sym_134 = 134'//new_line('a')// &
            'sym_135 = 135'//new_line('a')// &
            'sym_136 = 136'//new_line('a')// &
            'sym_137 = 137'//new_line('a')// &
            'sym_138 = 138'//new_line('a')// &
            'sym_139 = 139'//new_line('a')// &
            'sym_140 = 140'//new_line('a')// &
            'sym_141 = 141'//new_line('a')// &
            'sym_142 = 142'//new_line('a')// &
            'sym_143 = 143'//new_line('a')// &
            'sym_144 = 144'//new_line('a')// &
            'sym_145 = 145'//new_line('a')// &
            'sym_146 = 146'//new_line('a')// &
            'sym_147 = 147'//new_line('a')// &
            'sym_148 = 148'//new_line('a')// &
            'sym_149 = 149'//new_line('a')// &
            'sym_150 = 150'//new_line('a')// &
            'sym_151 = 151'//new_line('a')// &
            'sym_152 = 152'//new_line('a')// &
            'sym_153 = 153'//new_line('a')// &
            'sym_154 = 154'//new_line('a')// &
            'sym_155 = 155'//new_line('a')// &
            'sym_156 = 156'//new_line('a')// &
            'sym_157 = 157'//new_line('a')// &
            'sym_158 = 158'//new_line('a')// &
            'sym_159 = 159'//new_line('a')// &
            'sym_160 = 160'//new_line('a')// &
            'sym_161 = 161'//new_line('a')// &
            'sym_162 = 162'//new_line('a')// &
            'sym_163 = 163'//new_line('a')// &
            'sym_164 = 164'//new_line('a')// &
            'sym_165 = 165'//new_line('a')// &
            'sym_166 = 166'//new_line('a')// &
            'sym_167 = 167'//new_line('a')// &
            'sym_168 = 168'//new_line('a')// &
            'sym_169 = 169'//new_line('a')// &
            'sym_170 = 170'//new_line('a')// &
            'sym_171 = 171'//new_line('a')// &
            'sym_172 = 172'//new_line('a')// &
            'sym_173 = 173'//new_line('a')// &
            'sym_174 = 174'//new_line('a')// &
            'sym_175 = 175'//new_line('a')// &
            'sym_176 = 176'//new_line('a')// &
            'sym_177 = 177'//new_line('a')// &
            'sym_178 = 178'//new_line('a')// &
            'sym_179 = 179'//new_line('a')// &
            'sym_180 = 180'//new_line('a')// &
            'sym_181 = 181'//new_line('a')// &
            'sym_182 = 182'//new_line('a')// &
            'sym_183 = 183'//new_line('a')// &
            'sym_184 = 184'//new_line('a')// &
            'sym_185 = 185'//new_line('a')// &
            'sym_186 = 186'//new_line('a')// &
            'sym_187 = 187'//new_line('a')// &
            'sym_188 = 188'//new_line('a')// &
            'sym_189 = 189'//new_line('a')// &
            'sym_190 = 190'//new_line('a')// &
            'sym_191 = 191'//new_line('a')// &
            'sym_192 = 192'//new_line('a')// &
            'sym_193 = 193'//new_line('a')// &
            'sym_194 = 194'//new_line('a')// &
            'sym_195 = 195'//new_line('a')// &
            'sym_196 = 196'//new_line('a')// &
            'sym_197 = 197'//new_line('a')// &
            'sym_198 = 198'//new_line('a')// &
            'sym_199 = 199'//new_line('a')// &
            'sym_200 = 200'//new_line('a')// &
            'stop sym_200'//new_line('a')// &
            'end program main'

        test_200_symbols = expect_exit_status( &
            source, 200, &
            '/tmp/ffc_large_symbol_count_test')
    end function test_200_symbols

end program test_session_large_symbol_count_compiler
